### ISSUE TITLE
Több felhasználó

### ISSUE THREAD

**Issue by wizadow** [iso88592/neutest#14]
Ha több felhasználó lépett be egyszerre, akkor mindenki azt a felületet látja, aki utoljóra lépett be.
Ha az admin után lép be egy felhasználó, akkor az adminnak ez jelenik meg: 403: nem engedélyezett.

**Comment by iso88592** [comment]
There should be no subsequent but different logins from the same machine. 403 is acceptable as the user cannot violate access.
